language: node_js
env:
  global:
    - CI=true
cache: yarn
git:
  depth: 5
jobs:
  include:
    - stage: test
      node_js:
        - '10'
      script:
        - yarn test --runInBand --no-cache
    - stage: coverage
      node_js: '10'
      script:
        - yarn coveralls
    - stage: deploy ghpages
      node_js: '10'
      if: branch = master AND tag IS present
      script:
        - bash ./deploy-examples.sh
    - stage: npm release
      if: tag IS present
      node_js: '10'
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          branch: master
          tags: true
